import { FieldError, PlantDetails } from '../interfaces';

export const __prod__ = process.env.NODE_ENV === 'production';
export const INTERNAL_SERVER_ERROR: FieldError = {
    field: 'server',
    message: 'internal server error'
};

export const plants = [
    'maclura_pomifera',
    'ulmus_rubra',
    'prunus_virginiana',
    'acer_rubrum',
    'broussonettia_papyrifera',
    'prunus_sargentii',
    'ptelea_trifoliata',
    'ulmus_pumila',
    'abies_concolor',
    'asimina_triloba',
    'diospyros_virginiana',
    'quercus_montana',
    'ilex_opaca',
    'liriodendron_tulipifera',
    'acer_negundo',
    'styrax_japonica',
    'quercus_muehlenbergii',
    'aesculus_pavi',
    'juglans_cinerea',
    'chionanthus_virginicus',
    'catalpa_bignonioides',
    'cercis_canadensis',
    'ulmus_americana',
    'cryptomeria_japonica',
    'staphylea_trifolia',
    'acer_palmatum',
    'ostrya_virginiana',
    'fraxinus_nigra',
    'carya_cordiformis',
    'gleditsia_triacanthos',
    'tilia_cordata',
    'salix_nigra',
    'koelreuteria_paniculata',
    'catalpa_speciosa',
    'eucommia_ulmoides',
    'tsuga_canadensis',
    'platanus_occidentalis',
    'acer_saccharinum',
    'zelkova_serrata',
    'acer_saccharum',
    'magnolia_denudata',
    'carpinus_caroliniana',
    'pinus_cembra',
    'magnolia_virginiana',
    'carya_glabra',
    'quercus_marilandica',
    'taxodium_distichum',
    'cornus_florida',
    'quercus_alba',
    'pinus_bungeana',
    'malus_pumila',
    'pyrus_calleryana',
    'carya_tomentosa',
    'quercus_velutina',
    'quercus_stellata',
    'chamaecyparis_pisifera',
    'metasequoia_glyptostroboides',
    'pinus_parviflora',
    'salix_babylonica',
    'pinus_flexilis',
    'pinus_resinosa',
    'cladrastis_lutea',
    'picea_pungens',
    'quercus_acutissima',
    'picea_abies',
    'salix_caroliniana',
    'prunus_subhirtella',
    'quercus_michauxii',
    'magnolia_stellata',
    'oxydendrum_arboreum',
    'cedrus_libani',
    'populus_deltoides',
    'liquidambar_styraciflua',
    'salix_matsudana',
    'crataegus_viridis',
    'stewartia_pseudocamellia',
    'pinus_virginiana',
    'ulmus_parvifolia',
    'quercus_virginiana',
    'ficus_carica',
    'chamaecyparis_thyoides',
    'cornus_mas',
    'quercus_macrocarpa',
    'pinus_densiflora',
    'pinus_rigida',
    'nyssa_sylvatica',
    'aesculus_glabra',
    'quercus_nigra',
    'picea_orientalis',
    'pinus_taeda',
    'juglans_nigra',
    'populus_grandidentata',
    'pinus_echinata',
    'populus_tremuloides',
    'castanea_dentata',
    'pinus_nigra',
    'pinus_koraiensis',
    'pinus_peucea',
    'pinus_wallichiana',
    'ulmus_glabra',
    'tilia_americana',
    'cedrus_atlantica',
    'abies_nordmanniana',
    'pinus_pungens',
    'quercus_shumardii',
    'amelanchier_canadensis',
    'carya_ovata',
    'acer_pensylvanicum',
    'malus_baccata',
    'crataegus_pruinosa',
    'fagus_grandifolia',
    'pseudolarix_amabilis',
    'malus_hupehensis',
    'pinus_sylvestris',
    'magnolia_tripetala',
    'betula_alleghaniensis',
    'acer_ginnala',
    'malus_floribunda',
    'amelanchier_laevis',
    'malus_coronaria',
    'prunus_pensylvanica',
    'larix_decidua',
    'prunus_serotina',
    'magnolia_acuminata',
    'celtis_tenuifolia',
    'gymnocladus_dioicus',
    'phellodendron_amurense',
    'betula_populifolia',
    'quercus_bicolor',
    'robinia_pseudo-acacia',
    'tilia_tomentosa',
    'magnolia_macrophylla',
    'albizia_julibrissin',
    'acer_campestre',
    'halesia_tetraptera',
    'chionanthus_retusus',
    'crataegus_laevigata',
    'quercus_imbricaria',
    'quercus_robur',
    'morus_alba',
    'crataegus_phaenopyrum',
    'betula_jacqemontii',
    'cercidiphyllum_japonicum',
    'quercus_coccinea',
    'paulownia_tomentosa',
    'ginkgo_biloba',
    'acer_platanoides',
    'pinus_strobus',
    'betula_nigra',
    'platanus_acerifolia',
    'morus_rubra',
    'aesculus_hippocastamon',
    'prunus_yedoensis',
    'quercus_cerris',
    'tilia_europaea',
    'fraxinus_pennsylvanica',
    'magnolia_grandiflora',
    'cornus_kousa',
    'carpinus_betulus',
    'acer_pseudoplatanus',
    'quercus_palustris',
    'prunus_serrulata',
    'quercus_phellos',
    'celtis_occidentalis',
    'sassafras_albidum',
    'betula_lenta',
    'aesculus_flava',
    'amelanchier_arborea',
    'pinus_thunbergii',
    'acer_griseum',
    'ulmus_procera',
    'cedrus_deodara',
    'ailanthus_altissima',
    'crataegus_crus-galli',
    'evodia_daniellii',
    'juniperus_virginiana'
];

export const plantsMap: Record<string, PlantDetails> = {
    ulmus_rubra: {
        name: 'Ulmus Rubra(Slippery elm)',
        uses: [
            'Skin conditions: Slippery Elm is believed to be able to treat various skin conditions when applied topically',
            'Sore throat: Due to its natural demulcent properties, Slippery Elm is thought to soothe a sore throat by coating the lining of the throat and esophagus.',
            'Constipation: Slippery Elm may help relieve constipation.'
        ]
    },
    ulmus_pumila: {
        name: 'Ulmus Pumlia',
        uses: [
            'Skin conditions: Slippery Elm is believed to be able to treat various skin conditions when applied topically',
            'Sore throat: Due to its natural demulcent properties, Slippery Elm is thought to soothe a sore throat by coating the lining of the throat and esophagus.',
            'Constipation: Slippery Elm may help relieve constipation.'
        ]
    }
};
